// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpGgBdOPU8FG2CrbDVrXQ1mUKJ5pIhvM',
    appId: '1:979146667463:web:6244d536ff280c641895e2',
    messagingSenderId: '979146667463',
    projectId: 'pasanaku-cc88b',
    authDomain: 'pasanaku-cc88b.firebaseapp.com',
    storageBucket: 'pasanaku-cc88b.appspot.com',
    measurementId: 'G-F968MQ3N3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHYKcgDJMymGuTmrgMypqGYCPgd_GfA4',
    appId: '1:979146667463:android:37dca035c976e1a01895e2',
    messagingSenderId: '979146667463',
    projectId: 'pasanaku-cc88b',
    storageBucket: 'pasanaku-cc88b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNBPC6CMhhWCc1c9WX89BmygkRi82W18',
    appId: '1:979146667463:ios:10495ac2601065841895e2',
    messagingSenderId: '979146667463',
    projectId: 'pasanaku-cc88b',
    storageBucket: 'pasanaku-cc88b.appspot.com',
    iosBundleId: 'com.example.appPasanaku',
  );
}
